(* Declares the list of number *)
(* <variable> is the name *)
(* <number-set> is the data *)
<declaration> ::= "let" <variable> "=" <number-set> ";"
<number-set> ::= "[" <number-list> "]"
<number-list> ::= <number> | <number> "," <number-list>
<number>     ::= <digit> { <digit> }



(* Define addition expression*)
<expression> ::= <term> | <expression> "+" <term>
<term>       ::= <number>
(* expression example
    <expression>
    → <expression> "+" <term>
    → (<expression> "+" <term>) "+" <term>
    → (<term> "+" <term>) "+" <term>
*)
(*Divid expression*)
<divid expression> ::= <term> "/" <term>


(* This define that varibles can have letters and or numbers *)
<variable>   ::= <letter> { <letter> | <digit> }
<letter>     ::= "A" | ... | "Z" | "a" | ... | "z"
<digit>      ::= "0" | "1" | ... | "9"

(* What type of variable is the varible *)
<type>          ::= "number" | "string" | "boolean"