<program> ::= <statement> | <statement> <program>
<statement> ::= <declaration> | <forloop> | <addition> | <divid>
<declaration> ::= "let" <space> <variable> <space> "=" <space> <numberset> ";"

<numberset> ::= "[" <space> <numberlist> <space> "]"
<numberlist> ::= <number> 
               | <number> <space> "," <space> <numberlist>

<assignment> ::= <variable> <space> "=" <space> <addition> ";"
<forloop> ::= "for" <space> <variable> <space> "in" <space> <variable> <space> ":" <space> <assignment>

<addition> ::= <term> 
             | <addition> <space> "+" <space> <term>

<term> ::= <number>
<divid> ::= <term> <space> "/" <space> <term>
<number> ::= <digit> <digit>

<variable> ::= <letter> | <letter> <variable>

<letter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
            | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
            | "U" | "V" | "W" | "X" | "Y" | "Z"
            | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
            | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
            | "u" | "v" | "w" | "x" | "y" | "z"

<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<type> ::= "number" | "string" | "boolean"

<space> ::= " "
